### PR TITLE
fix: Fix quickstart error

### PR DESCRIPTION
**Pull request by hgschmie**
Seems that this field name changed.

## Checklist

- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x ] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
Hey, thank you for the PR. The linked file is actually correct as it is right now. What quickstart did you try?

**Comment by hgschmie** [comment]
I tried "git clone ... ; docker-compose ..." first; but this gives me 
```
Pulling consent (oryd/hydra-login-consent-node:v1.9.0-alpha.3.pre.1)...
ERROR: manifest for oryd/hydra-login-consent-node:v1.9.0-alpha.3.pre.1 not found: manifest unknown: manifest unknown
```

so I checked out the latest tag: 

```
git checkout  v1.9.0-alpha.3.pre.1
docker-compose -f quickstart.yml     -f quickstart-postgres.yml up
```
which dies with

```
hydra_1          | oidc.subject_identifiers: map[pairwise:map[salt:youReallyNeedToChangeThis] supported_types:[pairwise public]]
hydra_1          |                           ^-- additionalProperties "supported_types" not allowed
hydra_1          |
```

until I apply this patch.

**Comment by aeneasr** [comment]
Hey there - yes I think the problem is that the quickstart images were not successfully updated. I will do a release today so this should be fixed then!

**Comment by aeneasr** [comment]
The new release is out and this should be fixed!

**Pull request closed without merging**
