### PR TITLE
docs: use Ory instead of ORY in the documentation

### PR DESCRIPTION
**Pull request by gen1us2k**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further Comments

Update Ory Hydra documentation to follow styleguide

### CODE REVIEW

**Review by vinckr — COMMENTED** [review]
Thanks for looking into this!
Looking good 🎉 
The docs under /cli have to be changed elsewhere, it will be overwritten. 
Here you can find the CLI doc for `hydra clients create` for example: 
https://github.com/ory/hydra/blob/master/cmd/clients_create.go

**Comment by gen1us2k** [comment]
Okay. I'll fix it soon

**Comment by gen1us2k** [comment]
@vinckr I changed style in cmd folder. I think it can be a good idea(to change ORY to Ory in the whole project automatically using grep+sed). What do you think?

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
🙏

**Pull request merged**
