### PR TITLE
docker: update docker-compose to v3 + docker-compose files refactor

### PR DESCRIPTION
**Pull request by lopezator**
## Related issues

#1321 #1196

## Proposed changes

* Update docker-compose to v3.
* Reorganize/refactor docker-compose config into multiple files for cleanness and readability.

## About the second commit, reorganize/refactor...

I've detected six usecases of the docker-compose files.

1. postgres 
2. mysql
3. postgres + tracing
4. mysql + tracing
5. twoc-postgres
6. twoc-mysql

Instead of forcing the user to edit the `docker-compose.yml` and `docker-compose-twoc.yml` files by hand, the usage now would be:

1. docker-compose up --build
2. docker-compose -f docker-compose.yml -f docker-compose-mysql.yml up --build
3. docker-compose -f docker-compose.yml -f docker-compose-tracing.yml up --build
4. docker-compose -f docker-compose.yml -f docker-compose-mysql.yml -f docker-compose-tracing.yml up --build
5. docker-compose -f docker-compose-twoc.yml up --build
6. docker-compose -f docker-compose-twoc.yml -f docker-compose-twoc-mysql.yml up --build

## How does it work:

docker-compose does a merge between the files you pass  in via `-f`. So idea is to just override/modify the config as needed from base `docker-compose.yml`.

#### Advantages

* Cleaner to read.
* User doesn't have to touch files by hand to change the database or add tracing.

#### Disadvantages

* Commands are longer to type if you are not on standard configuration.
* Requires better docker-compose understanding if you want to tweak the files.

## Notes

* An edit of the docs would be required if this gets approved.
* I've tested all the described scenarios using `docker-compose config` and diff-ing the files with the produced output by the original config to ensure the behavior is the same on both scenarios.

CC \ @aeneasr

### CODE REVIEW

**Comment by aeneasr** [comment]
That's dope! We will have to [update the docs](https://github.com/ory/docs/blob/master/docs/hydra/5min-tutorial.md) to reflect those changes though! Would you be up to do that?

It might also be a good idea to include this

```
docker-compose up --build
docker-compose up -f docker-compose.yml -f docker-compose-mysql.yml --build
docker-compose up -f docker-compose.yml -f docker-compose-tracing.yml --build
docker-compose up -f docker-compose.yml -f docker-compose-mysql.yml -f docker-compose-tracing.yml --build
docker-compose up -f docker-compose-twoc.yml --build
docker-compose up -f docker-compose-twoc.yml -f docker-compose-twoc-mysql.yml --build
```

somewhere in the docs. Any suggestions?

**Comment by milesrichardson** [comment]
This is how I use docker-compose with my projects too. The commands can be pretty tedious to write (or realistically, copy/paste), though. Maybe worth wrapping them in a script?

**Comment by lopezator** [comment]
That's a great idea @milesrichardson, what do you think @aeneasr? 

And since english is not my native language, I also would appreciate help on where and how reflect in the docs the changes made here.

Maybe you could help in this matter @milesrichardson ?

**Comment by aaslamin** [comment]
Also related: https://github.com/ory/hydra/issues/1196

Nice work! As far as a script, perhaps a `Makefile` would make sense?

Something like `make run-with-mysql`, etc

**Comment by aeneasr** [comment]
Yeah, having that in a `Makefile` would be great!

**Comment by lopezator** [comment]
> Also related: #1196

Nice work! As far as a script, perhaps a Makefile would make sense?

Something like make run-with-mysql, etc

Cool. I think that closing this would close the linked issue also. This approach is slightly different, because extends is not supported on docker-compose v3, but equivalent.

**Comment by lopezator** [comment]
I ended up doing a bash script as it was cleaner IMHO. PTAL @aeneasr

**Comment by aeneasr** [comment]
The problem is that that won't work on windows (yeah those people exist...) :/ Do you have an idea how we could make it work for them too? I think especially for the 5 minutes guide that would be important. Alternatively, we'll do the 5 minutes tutorial with those docker commands and have the other stuff as a script or in the Makefile.

**Comment by aeneasr** [comment]
I'll come up with a solution - thank you for your hard work so far!

**Pull request merged**
