### PR TITLE
Update debug.mdx

### PR DESCRIPTION
**Pull request by shauryadhadwal**
OpenID Connect ID Token missing:
Add missing and important information about `nonce `claim when sending `response_type=id_token` in Implicit/Hybrid Flow.
If `nonce` is not included, any combination of `id_token` response_type fails in Implicit/Hybrid Flow.
The **error returned** is also not descriptive : 
`The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.`

With this change, many people can avoid searching the internet or using hit and trial like I had to.

## Checklist

- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x ] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you very much for your contribution to the documentation! Due to the way [Docusaurus](https://docusaurus.io) versioning works, you need to make the changes in two locations:

- `docs/versioned_docs/version-v{version}/path/to/file`
- `docs/docs/path/to/file`

Without making them in both locations, the changes will most likely be lost when releasing another version. Thank you! :)

**Comment by shauryadhadwal** [comment]
hey @aeneasr, 
I have made a commit to both 
docs/versioned_docs/version-v1.10/debug.mdx
and docs/docs/debug.mdx
as you suggested. 

Let me know anything else is required?

**Comment by aeneasr** [comment]
Thank you, this looks great! The CI is failing because some files are formatted incorrectly. To format them, run:

```
$ make format
$ git commit -a -m "styles: format code"
$ git push
```

Thank you!

**Comment by shauryadhadwal** [comment]
Will be creating a new pull request

**Pull request closed without merging**
