### PR TITLE
WIP feat: add username to introspect response

### PR DESCRIPTION
**Pull request by hisamura333**
## Related issue

[Need to add "username" key inside access_token ](https://github.com/ory/hydra/issues/1610)

I responded to the issue above.

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ ] I have read the [security policy](../security/policy)
- [ ] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation within the code base (if appropriate)
- [ ] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

## Further comments

It hasn't passed the test yet.

I'm getting multiple errors like the following, and I want to know how to deal with them.

```
--- FAIL: TestXXMigrations (22.06s)
    --- FAIL: TestXXMigrations/database=postgres (1.29s)
        clean_sql.go:10: Cleaning up database: pgx
        clean_sql.go:37: Successfully cleaned up database: pgx
        --- FAIL: TestXXMigrations/database=postgres/schema=1/run (0.74s)
            --- FAIL: TestXXMigrations/database=postgres/schema=1/run/up=8 (0.03s)
                --- FAIL: TestXXMigrations/database=postgres/schema=1/run/up=8/data=8 (0.02s)
                    helper.go:112: 
                                Error Trace:    helper.go:112
                                Error:          Received unexpected error:
                                                ERROR: column "username" of relation "hydra_oauth2_consent_request" does not exist (SQLSTATE 42703) handling 9_test
                                Test:           TestXXMigrations/database=postgres/schema=1/run/up=8/data=8
     

```

### CODE REVIEW

**Comment by aeneasr** [comment]
@zepatrik is currently working on improving the migrations and their tests. This looks like a typical migration bug. The work should be concluded next day, then we can rebase this and apply the patches and hopefully fix the issue right away :)

**Comment by zepatrik** [comment]
Hey @hisamura333 
The migration PR is finally done, can you adopt this PR to the new migration format? Basically you just have to split the migrations in two `*.up.sql` and `*.down.sql` files.
If you want you can also use the [fizz](https://github.com/gobuffalo/fizz) language instead (you will probably be able to have just one file for all databases then). The whole migrations moved to `persistence/sql` now.

**Comment by hisamura333** [comment]
@zepatrik 
All right.
I'll give it a try.

**Comment by vinckr** [comment]
Hey @hisamura333 , I don't want to bug you, but are you still fine with completing this PR?
I am trying to clean up our backlog of issues a little bit, so I am just inquiring how it looks on your end.

**Comment by hisamura333** [comment]
@vinckr
Sorry, the PR has stopped.
Thank you, we'd love to have you!

**Pull request closed without merging**
