### PR TITLE
feat: add front/backchannel logout params to client cli

### PR DESCRIPTION
**Pull request by mattbonnell**
## Related issue

#1487 

## Proposed changes

Adds client params related to OpenID Connect front/backchannel logout to the `hydra clients create` and `hydra clients update` CLI commands.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further comments

`make docs/cli` generated a _lot_ of changes in the docs, perhaps it hadn't been run in awhile.

### CODE REVIEW

**Comment by mattbonnell** [comment]
test failing on a `go.sum` diff, yet the PR doesn't contain any changes to `go.sum` 🤔

**Comment by aeneasr** [comment]
If you merge master into this branch, the CI should work!

**Comment by aeneasr** [comment]
Ah no sorry, I still have to fix something

**Comment by aeneasr** [comment]
Thank you, this looks great! The CI is failing because some files are formatted incorrectly. To format them, run:

```
$ make format
$ git commit -a -m "styles: format code"
$ git push
```

Thank you!

**Comment by mattbonnell** [comment]
> Thank you, this looks great! The CI is failing because some files are formatted incorrectly. To format them, run:
> 
> ```
> $ make format
> $ git commit -a -m "styles: format code"
> $ git push
> ```
> 
> Thank you!

Thanks! 

It seems like the Makefile is missing a `docs/node_modules` rule:
```
❯ make format
make: *** No rule to make target `docs/node_modules', needed by `format'.  Stop.
```

I ran the three commands in the `format` rule manually:
```
goimports -w --local github.com/ory .                                                                                                 
npm run format
cd docs; npm run format
```

Seems CI is still not happy 😢

**Comment by aeneasr** [comment]
Try

```
make node_modules
make docs/node_modules
make format
```

For me it formats:

```
        geändert:       docs/docs/concepts/consent.mdx
        geändert:       docs/docs/concepts/login.mdx
        geändert:       docs/docs/guides/consent.mdx
        geändert:       docs/docs/guides/login.mdx
        geändert:       docs/docs/guides/logout.mdx
        geändert:       docs/docs/reference/api.mdx
        geändert:       docs/scripts/rerelease.js
```

**Comment by mattbonnell** [comment]
> Try
> 
> ```
> make node_modules
> make docs/node_modules
> make format
> ```
> 
> For me it formats:
> 
> ```
>         geändert:       docs/docs/concepts/consent.mdx
>         geändert:       docs/docs/concepts/login.mdx
>         geändert:       docs/docs/guides/consent.mdx
>         geändert:       docs/docs/guides/login.mdx
>         geändert:       docs/docs/guides/logout.mdx
>         geändert:       docs/docs/reference/api.mdx
>         geändert:       docs/scripts/rerelease.js
> ```

```
❯ make node_modules
make: `node_modules' is up to date.
❯ make docs/node_modules
make: *** No rule to make target `docs/node_modules'.  Stop.
❯ make format
make: *** No rule to make target `docs/node_modules', needed by `format'.  Stop.
```

**Comment by aeneasr** [comment]
Looks like there's another makefile problem. Try:

```
npm i
npm run format
cd docs
npm i
npm run format
```

**Comment by mattbonnell** [comment]
Thanks @aeneasr, that did the trick!

**Comment by aeneasr** [comment]
Awesome, thank you! (:

**Pull request merged**
