### PR TITLE
fix: Fixed WWW-Authenticate header in userinfo handler

### PR DESCRIPTION
**Pull request by mitar**
## Proposed changes

Fixing the header value based on the spec.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
Could you please add a test case and also link the place in the RFC relevant to this?

**Comment by aeneasr** [comment]
Are you still up for the changes? :) If you need any help, let us know!

**Comment by mitar** [comment]
I documented the change. But as explained in #570, I do not know how or where to write a test for this.

**Comment by aeneasr** [comment]
The easiest way to find tests is to search for a unique string like "WWW-Authenticate". This will drop you at e.g. [here](https://github.com/ory/hydra/blob/master/oauth2/handler_test.go#L187-L195) which you could copy to add a test case for what you have changed :)

**Comment by mitar** [comment]
I updated tests.

**Review by aeneasr — APPROVED** [review]
Thank you! :))

**Pull request merged**
