### PR TITLE
api: add swagger api spec

### PR DESCRIPTION
**Pull request by arekkas**

### CODE REVIEW

**Comment by stevenroose** [comment]
Did you look at RAML while deciding on Swagger?

**Comment by arekkas** [comment]
Yes, swagger is OpenAPI spec so this is why it was chosen.

**Comment by stevenroose** [comment]
@arekkas The OpenAPI website confuses me. Is it an initiative to develop a new standard based on Swagger? Or is it just an alliance that pledges to use Swagger for it's APIs?

**Comment by arekkas** [comment]
OpenAPI spec **===** swagger 2.0 spec

**Comment by arekkas** [comment]
Superseded by #445

**Pull request closed without merging**
