### PR TITLE
Remove extraneous call to driver.init()

### PR DESCRIPTION
**Pull request by ludydoo**
in `janitor`, `driver.Init()` is called. Though this is already done in the `driver.factory`. 

## Checklist

- [X] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [X] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [X] I have read the [security policy](../security/policy).
- [X] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by Benehiko — CHANGES_REQUESTED** [review]
Nice! We would still need a `connection.Ping()` to the database in the `driver.init()`.

**Comment by ludydoo** [comment]
@Benehiko yeah that PR is just focused on removing the extraneous driver.Init(). gonna tackle the Ping in another PR

**Comment by Benehiko** [comment]
Thank you! :)
Tthen I will approve this one once all the tests pass.

**Review by aeneasr — APPROVED** [review]

**Comment by vinckr** [comment]
Hello @ludydoo 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)

**Pull request merged**
