### PR TITLE
Enable to validate by old system secret

### PR DESCRIPTION
**Pull request by sawadashota**
## Related issue

none

## Proposed changes

Enable to validate by old system secret when setting `ROTATED_SYSTEM_SECRET`.

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.md)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [hi@ory.sh](mailto:hi@ory.sh)) from the maintainers to push the changes.
- [x] I signed the [Developer's Certificate of Origin](https://github.com/ory/keto/blob/master/CONTRIBUTING.md#developers-certificate-of-origin)
by signing my commit(s). You can amend your signature to the most recent commit by using `git commit --amend -s`. If you
amend the commit, you might need to force push using `git push --force HEAD:<branch>`. Please be very careful when using
force push.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation within the code base (if appropriate)
- [ ] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

## Further comments

none

### CODE REVIEW

**Comment by aeneasr** [comment]
Could you explain in a few sentences what problem this solves?

**Comment by sawadashota** [comment]
OK,
this PR solves following issue

Set old system secret as environment variable `ROTATED_SYSTEM_SECRET` however hydra doesn't validate access token created before rotated system secret  

I found 2 causes

* Package `cmd` doesn't load environment variable `ROTATED_SYSTEM_SECRET`
* No codes inject HMACStrategy.RotatedGlobalSecrets rotated system secret

Therefore I created this PR!

**Comment by aeneasr** [comment]
That makes sense! It was intentional at first to not allow that but it makes sense. Thank you :)

**Comment by sawadashota** [comment]
Sorry for my poor description...
I will write more detail or create issue first next time!

**Comment by aeneasr** [comment]
Don't worry about it :)

**Pull request merged**
