### PR TITLE
fix: allow retries of unused login & consent requests

### PR DESCRIPTION
**Pull request by aeneasr**
Closes #2914
Closes #3085
See #2824

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
@jonkjenn can you confirm that this includes all the changes you wanted to make? There's still a few failing test cases I have to take a look at.

**Comment by jonkjenn** [comment]
> @jonkjenn can you confirm that this includes all the changes you wanted to make? There's still a few failing test cases I have to take a look at.

Looks good to me :+1:

**Comment by mig5** [comment]
@aeneasr 

Oh dang, I was hoping to see this in v1.11.8 :) Is there any reason it was only targeted for 2.x, since it's not really a feature, nor a breaking change, but in fact achieving consistency with what already exists for login flow in 1.x?

Thanks anyway for getting the fixes in...

**Comment by aeneasr** [comment]
Yes, we have freezed releases for v1.11 unless there's security things that need to be done as we work very hard to get Hydra 2.x out and need focus for that

**Pull request merged**
