### PR TITLE
feat: include amr claim in ID token

### PR DESCRIPTION
**Pull request by felixjung**
## Related issue(s)

Addresses #1756, as mentioned to @aeneasr in ory/fosite#625.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by felixjung** [comment]
I tried to add tests for this, but I'm not confident I found all the places where this would make sense.

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Comment by supercairos** [comment]
Hi, I'm not sure if it's related, but I have a bug while running Hydra's 5mins tutorial.
I get this error:
`message:missing destination name amr in *consent.ConsentRequest` while quering the Ory/Hydra admin consent request api
(https://github.com/ory/hydra-login-consent-node/blob/master/src/routes/consent.ts#L28)

I haven't found a workaround just yet... :(

**Comment by supercairos** [comment]
Ok, I've found the solution! 
Upgrading from Hydra 1.10.5 to Hydra 1.10.7 fixes the issue. 
Maybe the Hydra helm charts needs to be updated to use 1.10.7 ?

**Pull request merged**
