### PR TITLE
feat: Enable emittance of response time metrics (achieving parity with Kratos)

### PR DESCRIPTION
**Pull request by mbonnell-wish**
## Proposed changes

Currently, Kratos emits response time metrics that can be used to monitor latency as well as Requests Per Second. [Kratos's metrics middleware](https://github.com/ory/kratos/blob/master/metrics/prometheus/middleware.go#L19-L23) looks like:
```
func (pmm *MetricsManager) ServeHTTP(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	start := time.Now()
	next(rw, r)

	pmm.prometheusMetrics.ResponseTime.WithLabelValues(r.URL.Path).Observe(time.Since(start).Seconds())
}
```

Currently, the equivalent in Hydra omits the first and last lines:
```
func (pmm *MetricsManager) ServeHTTP(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	next(rw, r)
}
```
Consequently, Hydra doesn't emit the response time metrics that would enable us to monitor latency/RPS. 

In our case, being able to monitor these metrics is an absolute necessity, and generally, it would seem desirable to have parity between Hydra and Kratos in this regard. 

This PR adds the missing lines to Hydra to enable emittance of these key metrics and achieve parity with Kratos.
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by mbonnell-wish** [comment]
I'm trying to see the details on why the CircleCI tests are failing, but after authenticating I just get redirected to the CircleCI homepage. Is there something else I need to do to be able to view the details?

**Comment by aeneasr** [comment]
It's failing due to a missing `"time"` import :)

**Comment by mbonnell-wish** [comment]
@aeneasr thanks!

**Comment by mbonnell-wish** [comment]
@aeneasr fixed the issues, CI passing, ready for review :)

**Review by aeneasr — APPROVED** [review]
Awesome 🎉 

Thank you for your contribution!

**Comment by mbonnell-wish** [comment]
Hey @aeneasr, just wondering, when do you think you'd be able to publish a release containing this commit? I see that you made a release yesterday, so I *just* missed it. Would it be possible to release a patch containing this? We're hoping to take our Hydra-powered service into production in the next week and not having these metrics would be a blocker for us. Let me know at your convenience!

Thanks for all your hard work! 😄

**Comment by aeneasr** [comment]
We just released one yesterday I think - but I can sneak another one in ;)

**Comment by aeneasr** [comment]
It's out! https://github.com/ory/hydra/releases/tag/v1.9.2

**Comment by mbonnell-wish** [comment]
@aeneasr thanks so much for being so responsive, you're awesome 😍

**Comment by aeneasr** [comment]
Thank you for the contribution :)

**Pull request merged**
