### PR TITLE
feat: endpoint to delete login session by session id

### PR DESCRIPTION
**Pull request by aarmam**
This pull request introduces admin endpoint to delete login session by session id.

**Use case:**

1. User logs in from device/browser 1 to client application A. Hydra has created login session 1 (remember=true) and authenticated user.
2. User logs in from device/browser 1 to client application B
3. Login provider displays UI page with message "You have active sessions in following applications: Application A" and options 3.1) "Logout from all sessions and login as different user", 3.2) "Resume active sessions"
4. User selects 3.1 "Logout from all sessions and login as different user"
4.1 Login provider performs `DELETE /oauth2/auth/sessions/consent?subject=user1&login_session_id=session1&trigger_backchannel_logout=true` (related feature https://github.com/ory/hydra/pull/2844)
4.2 Login provider performs `DELETE /oauth2/auth/sessions/login/session1` (current feature)
4.3 Login provider request `GET /oauth2/auth/requests/login?login_challenge=a435b9e14cc04ee9a4b374b71e17397f` and uses request_url to redirect user to initiate new login request (Just to clarify where redirect url comes from. Actual request is made in step 3)

**Proposed feature allows to initiate new login with fewer redirects by skipping the usual logout flow.**

## Related issue(s)

https://github.com/ory/hydra/pull/2844

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]
🙏

**Comment by aeneasr** [comment]
Code looks good, but there are conflicts with master. Rebasing and regenerating the SDKs probably is enough to fix it!

**Comment by web-kat** [comment]
@aeneasr aside from being out of date with master, is there anything holding this body of work back?

**Comment by aarmam** [comment]
@web-kat @aeneasr I am closing this pull request because a similar pull request, #3450, has already been merged.

**Pull request closed without merging**
