### PR TITLE
fix: removed outdated information in doc configuration section

### PR DESCRIPTION
**Pull request by tnvmadhav**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further Comments

This fixes [#2452](https://github.com/ory/hydra/discussions/2452)

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you for these changes! Unfortunately almost all documents - except the Dockerfile - are autogenerated and need to fixed elsewhere. Here are some of those files:

- https://github.com/ory/docusaurus-template/blob/4f54031b6d278a92f89f4f6c6c968658a20bb547/scripts/config.js#L223
- https://github.com/ory/x/blob/a065f5780b6040793599f5d9fd68a246322b56ab/configx/helpers.go#L12

Also keep in mind that the $HOME behavior was changed only recently. I don’t recall which version exactly but it is the one where we introduced Koanf / the new config handling!

**Comment by tnvmadhav** [comment]
Thanks for the clarification 👍🏻

It seems that koanf was introduced with ory hydra v1.9.0  release 
🔗  https://github.com/ory/hydra/releases/tag/v1.9.0

That would mean that we need to maintain two versions of docusaurus-templates:

1. for ory hydra < v1.9.0         => with outdated info persisted
2. for ory hydra >= v1.9.0      => with outdated info removed

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
Great, thank you! Would you also be open to make the change to

https://github.com/ory/docusaurus-template/blob/4f54031b6d278a92f89f4f6c6c968658a20bb547/scripts/config.js#L223

? :)

**Comment by aeneasr** [comment]
Ah, nvm, I quickly removed it myself :)

**Pull request merged**
