### PR TITLE
fix: cockroach migration error when hydra upgrades v2

### PR DESCRIPTION
**Pull request by oninugarte**
## Related issue(s)

Referring to issue https://github.com/ory/hydra/issues/3535 this PR is intended to fix the Cockroach migration bug when upgrading Hydra from v1.11.10 to v2.
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
Thank you, this looks great! Could you please sign the CLA (just two clicks), then we can merge it right away!

**Comment by oninugarte** [comment]
Closes #3535

**Comment by zepatrik** [comment]
Hm we now get this error on master (also this PR):
```
            	            	ERROR: at or near "if": syntax error (SQLSTATE 42601)
            	            	error executing migrations/20211004110003000000_change_client_primary_key.cockroach.up.sql, sql: ALTER TABLE hydra_client DROP CONSTRAINT IF EXISTS "primary";
            	            	ALTER TABLE hydra_client ADD CONSTRAINT "hydra_client_pkey" IF NOT EXISTS PRIMARY KEY (pk);
```
Ideas how to resolve? Is a cockroach update enough?

**Comment by aeneasr** [comment]
Ok, in that case we need to revert this. My bad for overlooking that the tests failed. I'll revert it

**Comment by aeneasr** [comment]
I was also able to apply migrations from the start just now on Cockroach, so I think this is some other problem.

**Comment by zepatrik** [comment]
Also I figured the `IF NOT EXISTS` was added only in crdb v22.1 https://github.com/cockroachdb/cockroach/commit/e89093faf7225a635ddb5d4f260b20a4d8dd64e2
So we need to find a different way to make this work.

**Comment by zepatrik** [comment]
Hm not sure, the query should be
```sql
ALTER TABLE hydra_client DROP CONSTRAINT IF EXISTS "primary";
ALTER TABLE hydra_client ADD CONSTRAINT IF NOT EXISTS "hydra_client_pkey" PRIMARY KEY (pk);
```
according to the language spec https://www.cockroachlabs.com/docs/stable/alter-table.html

**Comment by zepatrik** [comment]
But we use some v20 in the tests, so I guess we should also bump that at some point, as a lot has happened since then.

**Comment by inigohu** [comment]
Can we re-apply this PR? 
Is there still a test using a lower version of cockroach v22.1?

**Pull request merged**
