### PR TITLE
Consent: deduplicate user authenticated clients during logout.

### PR DESCRIPTION
**Pull request by genchilu**
## Proposed changes

I adjust `ListUserAuthenticatedClientsWithFrontChannelLogout` & `ListUserAuthenticatedClientsWithBackChannelLogout`, make it return unduplicated clients.

If one user login client A 100 times, and then logout after the latest login, it would send 100 requests to the front/backchannel of client A with the logout token with the same sid. It's a waste of performance to both Hydra and client A.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)
- [x] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

### CODE REVIEW

**Comment by genchilu** [comment]
That's strange of the message of failure test is:
`Could not connect to database: parse mysql://root:test@(localhost:3306)/mysql?parseTime=true: invalid port ":3306)" after host`

**Comment by aeneasr** [comment]
The test failure is caused by a regression issue in the latest go releases. I fixed this in the upstream repo but have not had time yet to update the deps here. Will do so after the weekend, then this should pass!

**Comment by aeneasr** [comment]
This is now fixed on master - could you please rebase?

**Comment by aeneasr** [comment]
Awesome - thank you!

**Pull request merged**
