### PR TITLE
[oauth2] Flush refresh token/ auth code/ id token in FlushHandler 

### PR DESCRIPTION
**Pull request by genchilu**
## Proposed changes
Current FlushHandler in oauth2 only flush access token, but I think it should flush other tokens also.
ref: https://github.com/ory/hydra/issues/1574

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)
- [x] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! Unfortunately, this can not be merged as is. Removing refresh tokens will cause the refresh token chain to fail. It's important to keep track of all issued refresh tokens and access codes to be able to properly revoke them and their children later on. I believe this is true for OIDC as well.

We remove, iirc, used refresh tokens from the store anyways.

**Comment by genchilu** [comment]
It's fine.
DBA tell me that the size of tables is growing too fast, and all I can do now is delete data through pure SQL, that's not reasonable. That is why I submit this PR.

My original plan was to implement another method to clean expired data in hydra_oauth2_xxx_request  after this PR  merged. But I think that maybe not a good idea now, since it may cause the refresh token chain to fail, too.

Is there any plan to implement such kind of method to do housekeeping job? Or what may I help to make it happen?

**Comment by aeneasr** [comment]
Thanks for getting back to me. Which tables are growing too fast exactly? Maybe there is a missing cleanup job.

**Comment by genchilu** [comment]
hydra_oauth2_authentication_request is the table growing up the most.
The ratio of numbers of raw data in `hydra_oauth2_authentication_request`, `hydra_oauth2_authentication_session` and `other session/request/token table` is about to 4:2:1.

**Comment by aeneasr** [comment]
Ah ok I see - that makes sense - I think we can clean up those tables (and they are not properly being cleaned up at the moment), and it would not actually do a lot if we cleaned up the others instead.

I have to check if we're safe deleting those requests but I do believe so. The problem is that everytime someone calls `/oauth2/auth`, we create a new session and request, even if the user aborts the flow. That's why these are growing and why it's safe to remove those if they are simply "dead" requests. Would you be open to giving this a shot?

**Comment by genchilu** [comment]
Great, I will try it.
And please let me know if you make sure it's 100% safe deleting those requests, I really want to clean up DB through API, but not SQL in another system.

Thx a lot.

**Comment by aeneasr** [comment]
So from what I can tell right now, you can delete:

* All `hydra_oauth2_(authentication|consent)_request` that do not have a result for `hydra_oauth2_(authentication|consent)_request_handled.challenge = hydra_oauth2_(authentication|consent)_request.challenge` and where `hydra_oauth2_(authentication|consent)_request.requested_at` is older than a certain threshold.
* All `hydra_oauth2_logout_request` where `accepted=false`, `rejected=false`, `was_used=false` and (**this field needs to be added**) `requested_at` is older than a certain threshold.
* All `hydra_oauth2_(authentication|consent)_request` where one result exists for `hydra_oauth2_(authentication|consent)_request_handled.challenge = hydra_oauth2_(authentication|consent)_request.challenge` and where `hydra_oauth2_(authentication|consent)_request_handled.was_used=false` and `hydra_oauth2_(authentication|consent)_request.requested_at` is older than a certain threshold.

**Pull request closed without merging**
