### PR TITLE
5min-tutorial: fix docker-compose wrong restart values

### LINKED ISSUE #1312: docker-compose restart value is wrong
**Describe the bug**

docker-compose `restart: unless-stopped` is not a docker-compose v2 valid value.

**To Reproduce**

See here:

https://docs.docker.com/compose/compose-file/compose-file-v2/#restart

Valid values are: 

```yaml
  - restart: no
  - restart: always
  - restart: on-failure
```

`unless-stopped` is a docker-compose v3 restart value, see here:

https://docs.docker.com/compose/compose-file/#restart

**Expected behavior**

Either update docker-compose file to v3 or change the `restart: unless-stopped` values to other v2 applicable value.

### PR DESCRIPTION
**Pull request by lopezator**
replace unless-stopped values as they are not supported in used compose version (v2), for values supported in this compose version: on-failure. closes #1312.

CC\ @aeneasr

### CODE REVIEW

**Comment by lopezator** [comment]
I think it fits better in another PR, but would you be open to a migration to v3? It's much cleaner.

**Comment by lopezator** [comment]
Sorry, I deleted/closes this without intention.

**Comment by aeneasr** [comment]
Yeah, open to move to v3! Should we close this then?

**Comment by lopezator** [comment]
You can merge to correct the bug if you wish and I'll send the update to v3, sometime in the next week in an other PR.

**Comment by aeneasr** [comment]
ty!

**Comment by aeneasr** [comment]
and send over that v3 :)

**Pull request merged**
