### PR TITLE
fix: change comment on revokeOAuth2LoginSessions

### PR DESCRIPTION
**Pull request by sakai-303**
## Related issue(s)
This is not an issue, but the related discussions can be found below.
https://github.com/orgs/ory/discussions/118

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]

**Review by alnr — CHANGES_REQUESTED** [review]
Is this correct? I don't think it is. Need to look at this in detail.

**Comment by aeneasr** [comment]
This is correct, due to a cascade delete of request_id, see also: https://github.com/orgs/ory/discussions/118

**Comment by aeneasr** [comment]
```
CONSTRAINT hydra_oauth2_refresh_challenge_id_fk FOREIGN KEY (challenge_id) REFERENCES public.hydra_oauth2_flow(consent_challenge_id) ON DELETE CASCADE,
```

**Comment by alnr** [comment]
This PR is incorrect. Revoking a login session does not revoke access tokens and also does not revoke consent!

**Comment by alnr** [comment]
It also does not revoke refresh tokens.

**Comment by alnr** [comment]
Added comment in https://github.com/orgs/ory/discussions/118

**Comment by alnr** [comment]
Revert https://github.com/ory/hydra/pull/3858

**Pull request merged**
