### PR TITLE
propagate context through to the sql store

### PR DESCRIPTION
**Pull request by aaslamin**
With the introduction of https://github.com/ory/hydra/pull/1019 we will need to start propagating the request context down to sql store(s) so we can instrument our database calls. 

Notes:

- Creating the spans will be done in a follow-up PR. 
- Same thing will need to be done for the other handlers.

### CODE REVIEW

**Comment by aaslamin** [comment]
Unit tests pas for me locally.

**Comment by aeneasr** [comment]
Would it make sense to propagate context down to other stores too?

**Comment by aaslamin** [comment]
Yes, it definitely does. Would you like me to do this in this PR @aeneasr?

**Comment by aaslamin** [comment]
ℹ️ Update: 

• Client manager and handler have been updated to pass along context
• All consumers have also been updated accordingly

**Comment by aaslamin** [comment]
@aeneasr at this point I am a bit concerned that the PR is getting too large 😬. Could you review this as is and let me know if you want me to proceed with the Consent and JWK handlers in here or as a separate PR. 

They can be 🚀'ed independently.

**Comment by aeneasr** [comment]
It's definitely a bit larger, but that's fine as there's no functional change so it's very easy to review. So far this looks good to me!

**Comment by aeneasr** [comment]
Do you want to address the rest of the managers in this PR as well? You can also create another one - it doesn't really matter to me :) Maybe it's best to have the context in one commit (the one I'll squash when merging this)

**Comment by aaslamin** [comment]
**Update:** 

• JWK manager and all of it's clients have been updated

**Coming up:**

• Updating the JWTStrategy to pass along context where appropriate. Hopefully this doesn't get ugly 🤞 
• Updating Consent Manager (_this is a biggie_ 😨)

**Comment by aaslamin** [comment]
@aeneasr I believe the [JWTStrategy interface](https://github.com/ory/fosite/blob/master/token/jwt/jwt.go#L38-L45) in fosite needs to be updated to take in a context.

**Why?**

The implementation of this interface in Hydra makes calls to the db to fetch the latest keys:

- https://github.com/ory/hydra/blob/master/jwk/jwt_strategy.go#L75
- https://github.com/ory/hydra/blob/master/jwk/jwt_strategy.go#L83
- https://github.com/ory/hydra/blob/master/jwk/jwt_strategy.go#L91

The oauth handler consumes the Generate method.

Could you please confirm if this makes sense? If so that would be require:

- a PR in fosite to update the interface and any tests that break as a result
- a PR in Hydra to pull in the new version of fosite and update the JWTStrategy interface as necessary

**Comment by aaslamin** [comment]
**Update:**

Consent Manager and all of its clients have been updated to pass along context. All that is left is the JWT strategy which is pending feedback on the comment I left above. 

@aeneasr this PR is ready for review!

**Comment by aeneasr** [comment]
Ah yeah, that makes sense regarding JWT Strategy. It will also improve the API contract in fosite, which is using context almost everywhere anyways (well, except there and in bcrypt).

**Comment by aeneasr** [comment]
Wow this is massive! But looks good to me so far!

**Comment by aeneasr** [comment]
Thank you for your contribution!

**Pull request merged**
