### PR TITLE
change go-resty import path for gopkg.in/resty.v1

### PR DESCRIPTION
**Pull request by pierredavidbelanger**
Signed-off-by: Pierre-David Bélanger <pierredavidbelanger@gmail.com>

This is what we talked about in #1063

`go test ./...` is all `ok`

### CODE REVIEW

**Comment by aeneasr** [comment]
All tests are failing, please format and run `dep ensure`

**Comment by pierredavidbelanger** [comment]
indeed, i am sorry, hahaha, since i am using `go mod`, I forgot about `dep`,

**Comment by pierredavidbelanger** [comment]
I do not know why I had to manually edit `Gopkg.toml`, but it should work now.

I really am a newbe with Go `dep`

**Comment by aeneasr** [comment]
> I do not know why I had to manually edit Gopkg.toml, but it should work now.

That's fine :)

**Pull request merged**
