### PR TITLE
feat: allow configuring TTL in days

### PR DESCRIPTION
**Pull request by apexskier**
This allows configuring TTLs using more human readable formats (e.g. `30d` for refresh tokens instead of `720h`).

This should work, since internally these values are [parsed using `time.ParseDuration`](https://github.com/ory/hydra/blob/d455bf6b1dfce9f0e63038931d8a6bd5f43ff917/x/sqlx.go#L64).

## Related issue(s)

https://github.com/ory/hydra/issues/3461

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](https://github.com/ory/docs).

## Further context

I regenerated using `make sdk`

### CODE REVIEW

**Review by Loyalty84 — COMMENTED** [review]
spec/config.json

**Review by Loyalty84 — APPROVED** [review]
spec/config.json

**Comment by aeneasr** [comment]
`time.Parse` doesn't accept `d`: https://go.dev/play/p/8HoFvg0BTyY

**Comment by apexskier** [comment]
TIL I thought it did

**Pull request closed without merging**
