### PR TITLE
jwks: cors for wellknown endpoints

### PR DESCRIPTION
**Pull request by JiaLiPassion**
## Related issue
/.wellknown/jwks.json also need to handle cors.

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.md)
- [ ] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [hi@ory.sh](mailto:hi@ory.sh)) from the maintainers to push the changes.
- [ ] I signed the [Developer's Certificate of Origin](https://github.com/ory/keto/blob/master/CONTRIBUTING.md#developers-certificate-of-origin)
by signing my commit(s). You can amend your signature to the most recent commit by using `git commit --amend -s`. If you
amend the commit, you might need to force push using `git push --force HEAD:<branch>`. Please be very careful when using
force push.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation within the code base (if appropriate)
- [ ] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
Tests are failing because some method signature is broken

**Comment by JiaLiPassion** [comment]
@aeneasr, got it, I will run `go get ./...` and `go test`

**Comment by aeneasr** [comment]
That won't help, you need to update the signature of the handler (remove the httprouter.Params I think)

**Comment by JiaLiPassion** [comment]
@aeneasr, now the `test failed` because `e2e` test.
```
unknown shorthand flag: 'C' in -CgL8JuF6_g6g_tRCd9fRr9xGXhR5jPLD0zP5TyBU2k.NEtVUqesrmtvIXr15_6jPMOrzKAiYqs2rEA4DGeQc-0
```
Will continue to debug.

**Comment by aeneasr** [comment]
Thank you! This failing test is not caused by you :)

**Pull request merged**
