### PR TITLE
refactor: Updated Dockerfiles

### PR DESCRIPTION
**Pull request by adriang-90**
* I have changed some issues that I have found with *hadolint*, like condense **RUN** commands, changed **ADD** with **COPY** [nr 7](https://res.cloudinary.com/snyk/image/upload/v1551798390/Docker_Image_Security_Best_Practices_.pdf).

* I also deleted some lines in ``` RUN apk add --no-cache``` since it [should](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache) be okay that way.
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
Looks like there's a CVE in the new images:

https://github.com/ory/hydra/runs/5788382665?check_suite_focus=true#step:10:37

**Comment by adriang-90** [comment]
So was that alpine:3.15.1 the problem? Hmmm that's strange because I did not changed it so how did it pass the tests so far?

**Comment by aeneasr** [comment]
Thank you! Sometimes CVEs get found and break builds at random times, but your fixes look perfect now! :)

**Comment by vinckr** [comment]
Hello @adriang-90 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send all our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)

**Pull request merged**
