### PR TITLE
all: add support for cockroachdb

### PR DESCRIPTION
**Pull request by lopezator**
add cockroachdb support

## Related issue

https://github.com/ory/hydra/issues/990

### CODE REVIEW

**Comment by lopezator** [comment]
PTAL just to start discussing about this @aeneasr

**Comment by aeneasr** [comment]
Thank you for this PR! There's currently a major effort going on which will restructure how internals are instantiated: https://github.com/ory/hydra/pull/1314

Basically, there is a central "registry" (sort of like a ServiceLocator) which is responsible for setting up everything properly. This refactoring will also touch cockroachdb and might even make things a bit easier. I don't think there's a ton that needs to change in this PR for that but it would make sense to rebase on #1314 before merging this. Plan is to have the PR done either by today or by tomorrow, it's fairly far in terms of progress.

**Comment by lopezator** [comment]
Thanks @aeneasr! If that is so advanced I think I can put this on hold for a couple of days and rebase from master once merged.

**Comment by aeneasr** [comment]
I think that would be the best course of action!

**Pull request closed without merging**
