### PR TITLE
fix: Remove unnecessary transaction

### PR DESCRIPTION
**Pull request by mitar**
While resolving an issue in my own implementation of storage for Fosite which has been modeled after Hydra's, I realized:

* There is unnecessary transaction in this function. The first query (deleting expired assertions) is completely unrelated from the other one (inserting a new assertion). In fact, deletion could even be done as a background job and not inside this function (in fact, why it is not a background job, or in a goroutine).
* Transaction isolation level used here is a default one for the connection (i.e., read committed) while `BeginTX` uses `LevelRepeatableRead`. Is this on purpose or is this a bug? In my implementation I always used the same way to create a transaction so I always had repeatable read transactions, which combined with the unnecessary transaction in this function lead to commit conflicts (because multiple parallel transactions were attempting to delete same expired assertions).

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by aeneasr** [comment]
You're right,  that should indeed be a background task. But we can merge this as is already, thank you!

**Comment by mitar** [comment]
Note: are you sure it is OK that some transactions are not using `LevelRepeatableRead`? So you have to code paths here to create transactions and one has `LevelRepeatableRead` level and the other does not. Is this on purpose?

**Comment by mitar** [comment]
Sorry to nitpick, but "serializable" is the highest isolation level. :-)

Also, we had issues (and this is how I discovered this code) at a pretty low scale: it was pretty common to get "transaction aborted" with repeatable read before this code change, because the delete query touches the whole table, so two parallel queries had always a conflict.

Anyway, if you know what you are doing and why is `LevelRepeatableRead` even set there in the first place, then it is OK. :-)

**Comment by aeneasr** [comment]
I see, to be honest I haven't looked into the code in a while and it always requires cognitive load to do that. If this is an issue that is bothering you in production and is causing problems in delivering the service, please feel free to open an issue with a problem statement, reproducible case, and ideas on how to resolve it. If that's not the case I'll refrain from trying to think myself through this :)

**Comment by mitar** [comment]
No, issues on my side has been resolved. So this is all fine now. I just wanted to put this isolation-level discrepancy on your radar so that if in the future you might learn about some issue with isolation, you might remember that parts of queries are using one isolation level and parts another.

**Comment by mitar** [comment]
With some luck, I might also notice it and pitch in. :-)

Have a good night!

**Pull request merged**
