### PR TITLE
feat: flush refresh tokens for service oauth2/flush

### PR DESCRIPTION
**Pull request by naveenpaul1**
## Related issue

This changes are done based on the discussion happend on thread [https://github.com/ory/hydra/issues/1574#issuecomment-736684327](url)

 @aeneasr @Demonsthere 

## Proposed changes

flush expired refresh token along with access_token in `/oauth2/flush` service call, where condition remains same as access toke table deletion query

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Review by aeneasr — COMMENTED** [review]
This looks really good, thank you! @Benehiko can you take a look as well please?

What would be perfect as well would be a small test to check if the behaviour works as expected - you can probably add some code to this test: https://github.com/ory/hydra/blob/master/oauth2/handler_test.go#L131

**Review by Benehiko — COMMENTED** [review]
@aeneasr LGTM :)

**Comment by naveenpaul1** [comment]
updated the PR with unit test for access token scenario.
@aeneasr @Benehiko : please review

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Pull request merged**
