### PR TITLE
fix: link in documentation

### PR DESCRIPTION
**Pull request by Fantom409**
## Proposed changes
Currently, I receive a 404 error if I want to be redirected to 'Login flow page' via this link, this PR fix it

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by vinckr** [comment]
Thanks a lot for looking into this!
Your fix works, but unfortunately it is linking to the wrong document then, not the "version-v.1.10" one, but the "next version" one. 

I think you encountered this bug (https://github.com/ory/docusaurus-template/issues/38),
the correct [fix](https://github.com/ory/docs/#how-to-add-links-to-other-pages) would be to add the file extension to the link like so:
`../concepts/login.mdx`

If you could change that, would be stellar 🙏 

I will make a note to go over the documentation and fix all those links 🙂

**Review by vinckr — APPROVED** [review]
LGTM! 
Thanks 🎉

**Comment by aeneasr** [comment]
Thank you very much for your contribution to the documentation! Due to the way [Docusaurus](https://docusaurus.io) versioning works, you need to make the changes in two locations:

- `docs/versioned_docs/version-v{version}/path/to/file`
- `docs/docs/path/to/file`

Without making them in both locations, the changes will most likely be lost when releasing another version. Thank you! :)

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Pull request merged**
