### PR TITLE
sdk: fix swaggeroauth2_token_response (#1509)

### LINKED ISSUE #1509: Oauth2TokenResponse is parsing "response_uri", but not "expires_in"
**Describe the bug**

A response has wrong json tag:

```
type Swaggeroauth2TokenResponse struct {
.......
	// expires in
	ExpiresIn string `json:"redirect_uri,omitempty"`
.......
}
````

**Expected behavior**

```
type Swaggeroauth2TokenResponse struct {
.......
	// expires in
	ExpiresIn string `json:"expires_in,omitempty"`
.......
}
````

### PR DESCRIPTION
**Pull request by tyaps**
Fix wrong json attributes.
Add fields to parse whole response.

Closes #1509

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation within the code base (if appropriate)
- [ ] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)

### CODE REVIEW

**Comment by aeneasr** [comment]
Awesome, thank you for this! Unfortunately, this was changed at the wrong location - to fix that please update the values [here](https://github.com/ory/hydra/blob/master/oauth2/doc.go#L178) :)

**Comment by tyaps** [comment]
> Awesome, thank you for this! Unfortunately, this was changed at the wrong location - to fix that please update the values [here](https://github.com/ory/hydra/blob/master/oauth2/doc.go#L178) :)

Ok, I fixed it in oauth2/doc.go#L178 also ))

**Comment by aeneasr** [comment]
Thank you! Unfortunately I already addressed this with #1538 and re-generated also the sdk :) In any case - thank you for your contribution and welcome to the ORY family!

**Comment by tyaps** [comment]
Ok. But still I have a question. This response still haven't very useful fields like Id_token, refresh_token and scope. All these fields are exists in http response but not parsed in swaggeroauth2TokenResponse. Do you plan to include them later anyhow?

**Comment by aeneasr** [comment]
Yeah, I missed that - would you be open to a PR?

**Comment by tyaps** [comment]
Ok, I'll do ))
One question. I want also to add RefreshToken parameter to sdk/go/hydra/client/public/oauth2_token_parameters.go:62

It will allow us to refresh Access token by sending Refresh token. But I can't find the place where I can put this field (because oauth2_token_parameters.go is generated). Please, tell me where is it.))

**Comment by tyaps** [comment]
Ok, I've found it))

**Pull request closed without merging**
